### PR TITLE
docs: Add filter field libary sample for UpdateNotificationConfig

### PR DESCRIPTION
**Pull request by hannah-tsai**
Fixes b/155346619
Please merge this PR for me once it is approved and [cl/309855045] are both rolled out to prod.

### CODE REVIEW

**Review by JustinBeckwith — CHANGES_REQUESTED** [review]
Thanks for the PR!  Could I trouble you to run `npm run fix` locally, and re-push your change?

**Comment by hannah-tsai** [comment]
> Thanks for the PR! Could I trouble you to run `npm run fix` locally, and re-push your change?

Done! Thanks!

**Review by JustinBeckwith — APPROVED** [review]

**Comment by hannah-tsai** [comment]
Hi I want to follow up on this PR, I'm seeing codecov/project failure. I don't think the change list includes new files. Could you help on resolving this?

**Comment by JustinBeckwith** [comment]
That check is optional, and shouldn't block your PR from being merged.  You can safely ignore this :)

**Comment by hannah-tsai** [comment]
Thanks a lot!

**Pull request merged**
